<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('Permissions')->delete();
        
        \DB::table('Permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'login',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:57',
                'parent_id' => 45,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'logout',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'register',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'password.request',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'password.email',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'password.reset',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'password.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'home',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 0,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'role.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'role.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'role.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'role.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'role.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'role.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'role.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'permission.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'permission.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'permission.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'permission.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'permission.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'permission.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'permission.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'permission.add',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'permission.addmenu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'user.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 25,
                'icon' => NULL,
                'isURL' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'user.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 26,
                'icon' => NULL,
                'isURL' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'user.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 27,
                'icon' => NULL,
                'isURL' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'user.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 28,
                'icon' => NULL,
                'isURL' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'user.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 29,
                'icon' => NULL,
                'isURL' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'user.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 30,
                'icon' => NULL,
                'isURL' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'user.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 31,
                'icon' => NULL,
                'isURL' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'assignrole.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 32,
                'icon' => NULL,
                'isURL' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'assignrole.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 33,
                'icon' => NULL,
                'isURL' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'assignrole.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 34,
                'icon' => NULL,
                'isURL' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'assignrole.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 35,
                'icon' => NULL,
                'isURL' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'assignrole.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 36,
                'icon' => NULL,
                'isURL' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'assignrole.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 37,
                'icon' => NULL,
                'isURL' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'assignrole.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 38,
                'icon' => NULL,
                'isURL' => 1,
            ),
            38 => 
            array (
                'id' => 45,
                'name' => '#always',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:14:01',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 0,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 0,
            ),
            39 => 
            array (
                'id' => 46,
                'name' => '#usermanagement',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 09:25:56',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 8,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 0,
            ),
            40 => 
            array (
                'id' => 47,
                'name' => 'menu-index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            41 => 
            array (
                'id' => 48,
                'name' => 'menu-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            42 => 
            array (
                'id' => 49,
                'name' => 'menu-build-menu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            43 => 
            array (
                'id' => 50,
                'name' => 'menu-delete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            44 => 
            array (
                'id' => 51,
                'name' => 'menu-search',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            45 => 
            array (
                'id' => 52,
                'name' => 'display-name-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            46 => 
            array (
                'id' => 53,
                'name' => 'personal.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            47 => 
            array (
                'id' => 54,
                'name' => 'personal.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 53,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            48 => 
            array (
                'id' => 55,
                'name' => 'personal.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-12 08:05:19',
                'parent_id' => 53,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            49 => 
            array (
                'id' => 56,
                'name' => 'personal.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-12 08:05:19',
                'parent_id' => 53,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            50 => 
            array (
                'id' => 57,
                'name' => 'personal.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-12 08:05:19',
                'parent_id' => 53,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            51 => 
            array (
                'id' => 58,
                'name' => 'personal.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-12 08:05:20',
                'parent_id' => 53,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            52 => 
            array (
                'id' => 59,
                'name' => 'personal.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-26 04:06:02',
                'updated_at' => '2019-08-12 08:05:20',
                'parent_id' => 53,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            53 => 
            array (
                'id' => 60,
                'name' => 'debugbar.openhandler',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:53',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            54 => 
            array (
                'id' => 61,
                'name' => 'debugbar.clockwork',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            55 => 
            array (
                'id' => 62,
                'name' => 'debugbar.telescope',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            56 => 
            array (
                'id' => 63,
                'name' => 'debugbar.assets.css',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            57 => 
            array (
                'id' => 64,
                'name' => 'debugbar.assets.js',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            58 => 
            array (
                'id' => 65,
                'name' => 'debugbar.cache.delete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            59 => 
            array (
                'id' => 66,
                'name' => 'post.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            60 => 
            array (
                'id' => 67,
                'name' => 'post.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 66,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            61 => 
            array (
                'id' => 68,
                'name' => 'post.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 66,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            62 => 
            array (
                'id' => 69,
                'name' => 'personal.exportview',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-12 08:05:20',
                'parent_id' => 53,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            63 => 
            array (
                'id' => 70,
                'name' => 'qualification.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:50',
                'parent_id' => 0,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            64 => 
            array (
                'id' => 71,
                'name' => 'qualification.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 70,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            65 => 
            array (
                'id' => 72,
                'name' => 'qualification.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 70,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            66 => 
            array (
                'id' => 73,
                'name' => 'qualification.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:54',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 70,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            67 => 
            array (
                'id' => 74,
                'name' => 'qualification.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 70,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            68 => 
            array (
                'id' => 75,
                'name' => 'qualification.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 70,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            69 => 
            array (
                'id' => 76,
                'name' => 'qualification.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 70,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            70 => 
            array (
                'id' => 77,
                'name' => 'training.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 0,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            71 => 
            array (
                'id' => 78,
                'name' => 'training.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 77,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            72 => 
            array (
                'id' => 79,
                'name' => 'training.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 77,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            73 => 
            array (
                'id' => 80,
                'name' => 'training.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 77,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            74 => 
            array (
                'id' => 81,
                'name' => 'training.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 77,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            75 => 
            array (
                'id' => 82,
                'name' => 'training.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 77,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            76 => 
            array (
                'id' => 83,
                'name' => 'training.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 77,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            77 => 
            array (
                'id' => 84,
                'name' => 'transfer.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 0,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            78 => 
            array (
                'id' => 85,
                'name' => 'transfer.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:51',
                'parent_id' => 84,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            79 => 
            array (
                'id' => 86,
                'name' => 'transfer.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 84,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            80 => 
            array (
                'id' => 87,
                'name' => 'transfer.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 84,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            81 => 
            array (
                'id' => 88,
                'name' => 'transfer.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 84,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            82 => 
            array (
                'id' => 89,
                'name' => 'transfer.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 84,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            83 => 
            array (
                'id' => 90,
                'name' => 'transfer.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 84,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            84 => 
            array (
                'id' => 91,
                'name' => 'promotion.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 0,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            85 => 
            array (
                'id' => 92,
                'name' => 'promotion.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 91,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            86 => 
            array (
                'id' => 93,
                'name' => 'promotion.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 91,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            87 => 
            array (
                'id' => 94,
                'name' => 'promotion.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 91,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            88 => 
            array (
                'id' => 95,
                'name' => 'promotion.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 91,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            89 => 
            array (
                'id' => 96,
                'name' => 'promotion.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:55',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 91,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            90 => 
            array (
                'id' => 97,
                'name' => 'promotion.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 91,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            91 => 
            array (
                'id' => 98,
                'name' => 'leave.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 0,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            92 => 
            array (
                'id' => 99,
                'name' => 'leave.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 98,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            93 => 
            array (
                'id' => 100,
                'name' => 'leave.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 98,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            94 => 
            array (
                'id' => 101,
                'name' => 'leave.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 98,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            95 => 
            array (
                'id' => 102,
                'name' => 'leave.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 98,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            96 => 
            array (
                'id' => 103,
                'name' => 'leave.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 98,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            97 => 
            array (
                'id' => 104,
                'name' => 'leave.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 98,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            98 => 
            array (
                'id' => 105,
                'name' => 'status.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 0,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            99 => 
            array (
                'id' => 106,
                'name' => 'status.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 105,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            100 => 
            array (
                'id' => 107,
                'name' => 'status.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 105,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            101 => 
            array (
                'id' => 108,
                'name' => 'status.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 105,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            102 => 
            array (
                'id' => 109,
                'name' => 'status.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:52',
                'parent_id' => 105,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            103 => 
            array (
                'id' => 110,
                'name' => 'status.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 105,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            104 => 
            array (
                'id' => 111,
                'name' => 'status.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 105,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            105 => 
            array (
                'id' => 112,
                'name' => 'additional.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 0,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            106 => 
            array (
                'id' => 113,
                'name' => 'additional.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 112,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            107 => 
            array (
                'id' => 114,
                'name' => 'additional.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 112,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            108 => 
            array (
                'id' => 115,
                'name' => 'additional.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 112,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            109 => 
            array (
                'id' => 116,
                'name' => 'additional.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:56',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 112,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            110 => 
            array (
                'id' => 117,
                'name' => 'additional.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:57',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 112,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            111 => 
            array (
                'id' => 118,
                'name' => 'additional.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-08 09:11:57',
                'updated_at' => '2019-08-08 09:13:53',
                'parent_id' => 112,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            112 => 
            array (
                'id' => 119,
                'name' => 'personal.report',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-12 08:04:57',
                'updated_at' => '2019-08-12 08:05:19',
                'parent_id' => 53,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            113 => 
            array (
                'id' => 120,
                'name' => 'personal.search',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-12 10:31:15',
                'updated_at' => '2019-08-12 10:31:37',
                'parent_id' => 53,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            114 => 
            array (
                'id' => 121,
                'name' => 'personal.dashboard',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-13 04:18:09',
                'updated_at' => '2019-08-13 04:18:24',
                'parent_id' => 53,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            115 => 
            array (
                'id' => 122,
                'name' => 'personal.showByPin',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-14 06:47:31',
                'updated_at' => '2019-08-14 10:21:50',
                'parent_id' => 53,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            116 => 
            array (
                'id' => 123,
                'name' => 'personal.showByCouncil',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-14 06:47:31',
                'updated_at' => '2019-08-14 10:21:49',
                'parent_id' => 53,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            117 => 
            array (
                'id' => 124,
                'name' => 'personal.sendSMS',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-14 09:54:53',
                'updated_at' => '2019-08-14 10:21:50',
                'parent_id' => 53,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            118 => 
            array (
                'id' => 125,
                'name' => 'personal.reportdashboard',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-14 09:54:53',
                'updated_at' => '2019-08-14 10:21:50',
                'parent_id' => 53,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            119 => 
            array (
                'id' => 126,
                'name' => 'personal.searchbyinstitution',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-14 10:21:09',
                'updated_at' => '2019-08-14 10:21:49',
                'parent_id' => 53,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            120 => 
            array (
                'id' => 127,
                'name' => 'personal.searchbymun',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
            121 => 
            array (
                'id' => 128,
                'name' => 'personal.searchbygender',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            122 => 
            array (
                'id' => 129,
                'name' => 'personal.searchbydistrict',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            123 => 
            array (
                'id' => 130,
                'name' => 'personal.searchbypost',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            124 => 
            array (
                'id' => 131,
                'name' => 'personal.searchbyprovince',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 04:44:47',
                'parent_id' => 53,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            125 => 
            array (
                'id' => 132,
                'name' => 'personal.searchbystatus',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            126 => 
            array (
                'id' => 133,
                'name' => 'personal.searchbyexperience',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 04:43:40',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            127 => 
            array (
                'id' => 134,
                'name' => 'personal.searchbytraining',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-18 06:50:34',
                'updated_at' => '2019-08-18 06:50:44',
                'parent_id' => 53,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
        ));
        
        
    }
}