<?php

use Illuminate\Database\Seeder;

class PersonalInformationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('personal_informations')->delete();
        
        \DB::table('personal_informations')->insert(array (
            0 => 
            array (
                'id' => 8,
                'full_name_en' => 'Rushal',
                'full_name_np' => NULL,
                'dob_en' => '2019-07-16',
                'dob_np' => NULL,
                'gender' => '0',
                'religion' => '2',
                'group' => '3',
                'email' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'marital_status' => NULL,
                'permanent_pradesh' => 4,
                'temporary_pradesh' => 3,
                'permanent_district' => 1,
                'temporary_district' => 2,
                'permanent_local_auth' => 5,
                'temporary_local_auth' => 2,
                'permanent_ward' => 10,
                'temporary_ward' => 5,
                'created_at' => '2019-07-25 10:24:00',
                'updated_at' => '2019-08-04 10:29:16',
                'pin' => 666,
                'temporary_full_address' => 'New Road',
                'permanent_full_address' => 'New Road',
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            1 => 
            array (
                'id' => 21,
                'full_name_en' => 'Bishnu Manandhar',
                'full_name_np' => NULL,
                'dob_en' => '1961-08-03',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '0',
                'group' => '1',
                'email' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'marital_status' => 'Married',
                'permanent_pradesh' => 4,
                'temporary_pradesh' => 2,
                'permanent_district' => 14,
                'temporary_district' => 1,
                'permanent_local_auth' => 11,
                'temporary_local_auth' => 1,
                'permanent_ward' => 9,
                'temporary_ward' => 6,
                'created_at' => '2019-08-01 04:20:54',
                'updated_at' => '2019-08-04 10:09:02',
                'pin' => 667,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => '696969',
            ),
            2 => 
            array (
                'id' => 22,
                'full_name_en' => 'Kumari Shakya',
                'full_name_np' => NULL,
                'dob_en' => '1937-08-04',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '1',
                'group' => '3',
                'email' => NULL,
                'phone' => '98419841',
                'mobile' => '98419851',
                'marital_status' => 'Married',
                'permanent_pradesh' => 1,
                'temporary_pradesh' => 5,
                'permanent_district' => 1,
                'temporary_district' => 1,
                'permanent_local_auth' => 1,
                'temporary_local_auth' => 1,
                'permanent_ward' => 2,
                'temporary_ward' => 7,
                'created_at' => '2019-08-01 04:42:59',
                'updated_at' => '2019-08-04 10:09:30',
                'pin' => 668,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            3 => 
            array (
                'id' => 23,
                'full_name_en' => 'Kailash Kher',
                'full_name_np' => NULL,
                'dob_en' => '1959-08-14',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '2',
                'group' => '4',
                'email' => NULL,
                'phone' => NULL,
                'mobile' => '98419841',
                'marital_status' => 'Single',
                'permanent_pradesh' => 2,
                'temporary_pradesh' => 1,
                'permanent_district' => 20,
                'temporary_district' => 2,
                'permanent_local_auth' => 11,
                'temporary_local_auth' => 22,
                'permanent_ward' => 10,
                'temporary_ward' => 9,
                'created_at' => '2019-08-01 05:29:04',
                'updated_at' => '2019-08-04 10:20:22',
                'pin' => 669,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            4 => 
            array (
                'id' => 24,
                'full_name_en' => 'Rojen Pradhan',
                'full_name_np' => NULL,
                'dob_en' => '1954-10-23',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '2',
                'group' => '3',
                'email' => NULL,
                'phone' => '98411',
                'mobile' => '98510000',
                'marital_status' => 'Married',
                'permanent_pradesh' => 2,
                'temporary_pradesh' => 2,
                'permanent_district' => 46,
                'temporary_district' => 57,
                'permanent_local_auth' => 32,
                'temporary_local_auth' => 35,
                'permanent_ward' => 10,
                'temporary_ward' => 9,
                'created_at' => '2019-08-01 05:42:11',
                'updated_at' => '2019-08-04 10:20:56',
                'pin' => 670,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            5 => 
            array (
                'id' => 25,
                'full_name_en' => 'Mandira Bohara',
                'full_name_np' => NULL,
                'dob_en' => '1961-03-30',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '4',
                'group' => '6',
                'email' => NULL,
                'phone' => '98412626262',
                'mobile' => NULL,
                'marital_status' => 'Single',
                'permanent_pradesh' => 3,
                'temporary_pradesh' => 1,
                'permanent_district' => 40,
                'temporary_district' => 76,
                'permanent_local_auth' => 433,
                'temporary_local_auth' => 91,
                'permanent_ward' => 10,
                'temporary_ward' => 5,
                'created_at' => '2019-08-01 05:54:38',
                'updated_at' => '2019-08-04 09:54:10',
                'pin' => 671,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            6 => 
            array (
                'id' => 26,
                'full_name_en' => 'Asta Narayan',
                'full_name_np' => NULL,
                'dob_en' => '1945-08-01',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '3',
                'group' => '2',
                'email' => NULL,
                'phone' => NULL,
                'mobile' => '98510000',
                'marital_status' => 'Married',
                'permanent_pradesh' => 2,
                'temporary_pradesh' => 3,
                'permanent_district' => 1,
                'temporary_district' => 75,
                'permanent_local_auth' => 277,
                'temporary_local_auth' => 287,
                'permanent_ward' => 10,
                'temporary_ward' => 20,
                'created_at' => '2019-08-01 06:17:47',
                'updated_at' => '2019-08-04 10:21:05',
                'pin' => 672,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            7 => 
            array (
                'id' => 27,
                'full_name_en' => 'Jagriti Sapkota',
                'full_name_np' => NULL,
                'dob_en' => '1983-04-14',
                'dob_np' => NULL,
                'gender' => '1',
                'religion' => '3',
                'group' => '2',
                'email' => NULL,
                'phone' => NULL,
                'mobile' => '9898998',
                'marital_status' => 'Single',
                'permanent_pradesh' => 3,
                'temporary_pradesh' => 1,
                'permanent_district' => 19,
                'temporary_district' => 1,
                'permanent_local_auth' => 173,
                'temporary_local_auth' => 1,
                'permanent_ward' => 5,
                'temporary_ward' => 7,
                'created_at' => '2019-08-01 06:35:54',
                'updated_at' => '2019-08-04 10:10:01',
                'pin' => 673,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            8 => 
            array (
                'id' => 28,
                'full_name_en' => 'Bikram KC',
                'full_name_np' => NULL,
                'dob_en' => '2019-08-04',
                'dob_np' => '2076-04-19',
                'gender' => '1',
                'religion' => '0',
                'group' => '0',
                'email' => 'bmp@bmpinfology.com',
                'phone' => '984111323',
                'mobile' => '9843131',
                'marital_status' => 'Single',
                'permanent_pradesh' => 3,
                'temporary_pradesh' => 3,
                'permanent_district' => 27,
                'temporary_district' => 27,
                'permanent_local_auth' => 288,
                'temporary_local_auth' => 288,
                'permanent_ward' => 6,
                'temporary_ward' => 6,
                'created_at' => '2019-08-04 06:22:08',
                'updated_at' => '2019-08-08 06:18:48',
                'pin' => 674,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            9 => 
            array (
                'id' => 45,
                'full_name_en' => 'test',
                'full_name_np' => NULL,
                'dob_en' => NULL,
                'dob_np' => NULL,
                'gender' => NULL,
                'religion' => NULL,
                'group' => NULL,
                'email' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'marital_status' => NULL,
                'permanent_pradesh' => NULL,
                'temporary_pradesh' => NULL,
                'permanent_district' => NULL,
                'temporary_district' => NULL,
                'permanent_local_auth' => NULL,
                'temporary_local_auth' => NULL,
                'permanent_ward' => NULL,
                'temporary_ward' => NULL,
                'created_at' => '2019-08-12 06:19:31',
                'updated_at' => '2019-08-12 06:19:31',
                'pin' => NULL,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'trillectro-aaron-campbell-1366×768_1565590771.jpg',
                'council' => NULL,
                'council_number' => NULL,
                'pis_number' => NULL,
            ),
            10 => 
            array (
                'id' => 46,
                'full_name_en' => 'test3',
                'full_name_np' => NULL,
                'dob_en' => NULL,
                'dob_np' => NULL,
                'gender' => NULL,
                'religion' => NULL,
                'group' => NULL,
                'email' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'marital_status' => NULL,
                'permanent_pradesh' => NULL,
                'temporary_pradesh' => NULL,
                'permanent_district' => NULL,
                'temporary_district' => NULL,
                'permanent_local_auth' => NULL,
                'temporary_local_auth' => NULL,
                'permanent_ward' => NULL,
                'temporary_ward' => NULL,
                'created_at' => '2019-08-13 06:32:58',
                'updated_at' => '2019-08-13 06:32:58',
                'pin' => NULL,
                'temporary_full_address' => NULL,
                'permanent_full_address' => NULL,
                'image' => 'no.jpg',
                'council' => 1,
                'council_number' => '363636',
                'pis_number' => NULL,
            ),
        ));
        
        
    }
}